runtime: nodejs20

instance_class: F2

env_variables:
  SUPABASE_URL: "https://temlyqdfvdujiilwiwof.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbWx5cWRmdmR1amlpbHdpd29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTY2NTgzNDEsImV4cCI6MjAxMjIzNDM0MX0.pS0bdksPkHzRXPbYrMjNw0ULyORw8Z_GLeZ5mhR9u08"
  SUPABASE_JWT_SECRET: "onTVjDxliMWoa7WkPrWKd4GBe+tyUZvgT3GREQ0bcjr/JKGByGjehD6VOVz+QOBZA44ZlSdGZ+usGdZraWisZA=="

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto